### ISSUE TITLE
Fixing the Arch package

### ISSUE THREAD

**Issue by SunRed** [insanengineer/touchpad-disabler#1]
Like already mentioned [here](https://aur.archlinux.org/packages/touchpad-disabler) the Arch package needs some fixes, I'll just quote myself here:

> This is a really good package, but I would suggest using this PKGBUILD file:
> http://pastebin.com/6qVmWSYS
> with this .install file:
> http://pastebin.com/XNuFwbGs
> 
> Or something like that. Also the application won't start because the gshema file is missing and just place the touchpad-disabler executable in /usr/bin rather than /opt since /opt is mostly used for (proprietary) applications that are already built as a whole package.

The suggested PKGBUILD file already "fixes" these two things mentioned. But when moving the executable to /usr/bin just take in mind that [touchpad-disabler.desktop](https://github.com/insanengineer/touchpad-disabler/blob/8da5883f9f0a492befbcad5c01bef750f68268d5/touchpad-disabler.desktop#L3) needs to be updated as well.

**Comment by insanengineer** [comment]
Thank you for all the great suggestion. I am in process of updating the Arch package with your recommended changes.
