### ISSUE TITLE
ETPS/2 Elantech Touchpad is not disabled

### ISSUE THREAD

**Issue by ghost** [insanengineer/touchpad-disabler#2]
ETPS/2 Elantech Touchpad is not disabled when I plug in my mouse.

The notification says it was disabled, though.

My laptop is Dell Inspiron 7520, OS: Arch GNU/Linux

**Comment by insanengineer** [comment]
I will see what I can find out and let you know. Since I do not have that particular laptop it will take some research. Thanks for the bug report.

**Comment by ghost** [comment]
@insanengineer if you need me to do something to help you with the research, I am more than eager to do it.

**Comment by insanengineer** [comment]
Sounds good. What destop envronment are you running and are you running wayland or x11?

**Comment by ghost** [comment]
@insaneengineer Xfce 4.12 on X11

**Comment by insanengineer** [comment]
Can you please run xinput --list and post the result?

**Comment by ghost** [comment]
$ xinput --list
⎡ Virtual core pointer                        id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                  id=13   [slave  pointer  (2)]
⎜   ↳ A4Tech USB Mouse                          id=10   [slave  pointer  (2)]
⎣ Virtual core keyboard                       id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard                 id=5    [slave  keyboard (3)]
    ↳ Power Button                                id=6    [slave  keyboard (3)]
    ↳ Video Bus                                   id=7    [slave  keyboard (3)]
    ↳ Power Button                                id=8    [slave  keyboard (3)]
    ↳ Video Bus                                   id=9    [slave  keyboard (3)]
    ↳ Laptop_Integrated_Webcam_HD                 id=11   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard                id=12   [slave  keyboard (3)]
    ↳ Dell WMI hotkeys                            id=14   [slave  keyboard (3)]

**Comment by insanengineer** [comment]
Ok. Now lets try running synclient TouchpadOff=1. This should disable the touchpad and synclient TouchpadOff=0 should enable it. Do the commands work?

**Comment by ghost** [comment]
I do not have this command installed.
The package maintainer should add `xf86-input-synaptics` package to dependecies.
And after installation Touchpad Disabler still does not work.

**Comment by ghost** [comment]
Is it alright if I submit a patch using that `synclient` command?

**Comment by insanengineer** [comment]
If you would like. I have a synclient function already in the code that would make it easy implement. I use the xinput method like this xinput set-prop 12 "Device Enabled" 0. Were 12 is the id of the device that is obtained bt the xinput --list command. Change 0 to 1 to re-enable the touchpad. Does this command work?

**Comment by ghost** [comment]
@insanengineer I changed your `set_touchpad_xinput_state` to use the `synclient` command.
You also should follow some defined coding style cause that mix of spaces and tabs is a mess.

I personally recommend using GNU C Style.
